package com.quant.making.audit;

public enum AuditEventType {
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CANCELLED,
    ORDER_FILLED,
    QUOTE_GENERATED,
    QUOTE_CANCELLED,
    QUOTE_EXPIRED,
    TRADE_EXECUTED,
    RISK_CHECK_PASSED,
    RISK_CHECK_BLOCKED,
    POSITION_UPDATED,
    BALANCE_CHANGED,
    SYSTEM_SNAPSHOT,
    CONFIGURATION_CHANGED,
    ERROR_OCCURRED,
    WARNING_ISSUED
}